errors: provide a default empty error_map [+]
This is done so that any inheriting ResourceConfig
can reliably do:

```python
class CustomResourceConfig(ResourceConfig):
    error_map = {
        **ResourceConfig.error_map,
        CustomException: custom_handler
    }
```